// THOUGHTS REOUTES

// GET ALL THOUGHTS

// GET THOUGHTS BY ITS ID

// POST TO CREATE A NEW THOUGHT ASSOCIATE THOUGHT WITH ITS USER

// PUT TO UPDATE THOUGHT BY ITS ID

// DELETE TO REMOVE THOUGHT BY ITS ID

// POST TO CREATE REACTION STORED IN SINGLE THOUGHTS ARRAY

// DELETE TO PULL AND REMOVE REACTION FROM THOUGHTS ARRAY BY REACTIONID