// USERS/ROUTES

// GET ALL

// GET SINGLE BY ID(with friends and thoughts data)

// POST NEW USER

// POST TO UPDATE USER BY ID

// DELETE TO REMOVE USER BY ID

// POST TO ADD NEW FRIEND TO USER FRIENDS LIST

// DELETE TO REMOVE FRIENDS FROM USERS FRIEND LIST